### ISSUE TITLE
how to use the gitlab oauth 

### ISSUE THREAD

**Issue by mxq0923** [shimohq/mogo#80]
how to set in gitlab applications?

**Comment by sevennt** [comment]
visit https://<GIT-URL>/admin/applications，then set application parameters, get your application clientID and clientSecret and put them to your mogo configuration file.

```toml
...
[[auth.tps]]
typ = "gitlab"
enable = true
allowSignUp = true
clientId = "ClientID" # change <ClientID> with your application clientID
clientSecret = "ClientSecret" # change <ClientSecret> with your application clientSecret
scopes = ["api"]
authUrl = "https://<GIT-URL>/oauth/authorize"  # change <GIT-URL> with your gitlab host
tokenUrl = "https://<GIT-URL>/oauth/token"      # change <GIT-URL> with your gitlab host
apiUrl = "https://git.shimo.im/api/v4"
allowedDomains = []
teamIds = []
allowedOrganizations = []
```
